Wallstreet/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('youcantfindit/', admin.site.urls),
    path('', include("bazaar.urls"))
]

bazaar/urls.py
from django.urls import path
from . import views

app_name = 'bazaar'
urlpatterns = [
    path('gotaot/', views.Register.as_view(), name='register'),
    path('login/', views.Login.as_view(),name='login'),
    path('logoff/', views.Logoff, name='logoff'),
    path('', views.postlogin.as_view(), name='index'),
    path('company/', views.CompanyView.as_view(), name='company'),
    path('buy/', views.Buy.as_view(), name='buy'),
    path('sell/', views.Sell.as_view(), name='sell'),
    path('news/', views.NewsView.as_view(), name='news'),
    path('transactions/', views.Transactions.as_view(), name='transactions'),
    path('leaderboard/', views.LeaderBoardView.as_view(), name='leaderboard'),
]

bazaar/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator

from datetime import datetime
# prBxkV

# User share table and User history - Improve Efficiency

# Create your models here.


class Global(models.Model):
    # Global Table
    sensex = models.FloatField(default=0)
    spread = models.IntegerField(default=0)
    LiveText = models.CharField(max_length=100)
    LeaderboardSize = models.IntegerField(default=100)
    LeaderBoardUpdateTime = models.DateTimeField(default=datetime.now)
    bidRangePercent = models.IntegerField(
        default=10, validators=[MaxValueValidator(100),
                                MinValueValidator(1)])
    registrationKey = models.CharField(max_length=20, default="abcde")
    startStopMarket = models.BooleanField(
        default=True)  # True => start, False => Stop
    startNews = models.BooleanField(default=False)
    NewsCounter = models.IntegerField(default=0)


class Profile(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE)  # Extending User Model
    rank = models.IntegerField(default=-1)  # Rank of the user
    numberOfShares = models.IntegerField(
        default=0)  # Number of shares owned by the user
    cash = models.IntegerField(default=200000)  # Cash remaining
    netWorth = models.IntegerField(
        default=0)  # Users networth; Required for leaderboard;

    # Calculated using cash and number of shares

    def __str__(self):
        return self.user.username


class Company(models.Model):
    # Table to store all the company data
    name = models.CharField(max_length=25)  # Name of the company
    tempName = models.CharField(max_length=25)
    sharePrice = models.IntegerField(default=0)  # Company's share price
    totalNoOfShares = models.IntegerField(
        default=0)  # Total number of shares available for sale
    sharesLeft = models.IntegerField(
        default=0
    )  # Number of shares left  ########(Redundant?)ny.objects.all()

    def __str__(self):
        return self.name


class UserShareTable(models.Model):
    # Table to store shares owned by the user
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)  # User
    company = models.ForeignKey(Company, on_delete=models.CASCADE)  # Company
    bidShares = models.IntegerField(default=0)  # Number of Shares owned

    def __str__(self):
        return str(self.profile) + ", " + str(
            self.company) + ", number: " + str(self.bidShares)


class UserHistory(models.Model):
    # Table to store transaction history of user
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)  # User
    company = models.ForeignKey(Company, on_delete=models.CASCADE)  # Company
    bidShares = models.IntegerField(default=0)  # Number of shares bought/sold
    bidPrice = models.IntegerField(
        default=0)  # Price at which shares were bought/sold
    buySell = models.BooleanField(
        default=1)  # Bought/sold flag; buy = 1, sell = 0
    transactionTime = models.DateTimeField(
        default=datetime.now)  # Transaction Time

    def __str__(self):
        return str(self.profile) + ", " + str(self.company) + ", Buy: " + str(
            self.buySell) + ", bidPrice: " + str(
                self.bidPrice) + ", bidShares: " + str(self.bidShares)


class BuyTable(models.Model):
    # Table to store buy requests
    company = models.ForeignKey(Company, on_delete=models.CASCADE)  # Company
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)  # User
    bidPrice = models.IntegerField(default=0)  # Buy Price
    bidShares = models.IntegerField(default=0)  # Number of shares
    transactionTime = models.DateTimeField(
        default=datetime.now)  # Transaction Time


class SellTable(models.Model):
    # Table to store sell requests
    company = models.ForeignKey(Company, on_delete=models.CASCADE)  # Company
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)  # User
    bidPrice = models.IntegerField(default=0)  # Sell Price
    bidShares = models.IntegerField(default=0)  # Number of shares
    transactionTime = models.DateTimeField(
        default=datetime.now)  # Transaction Time


class News(models.Model):
    # Table to store news
    title = models.CharField(max_length=50)
    description = models.CharField(max_length=200)
    time = models.DateTimeField(default=datetime.now)

    def __str__(self):
        return self.title


class LeaderBoard(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.profile)


try:
    for i in Company.objects.all():
        exec("""
class BuyTable_""" + i.tempName + """(models.Model):
    # Table to store buy requests
    company = models.IntegerField(default=""" + str(i.pk) + """)  # Company
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)  # User
    bidPrice = models.IntegerField(default=0)  # Buy Price
    bidShares = models.IntegerField(default=0)  # Number of shares
    transactionTime = models.DateTimeField(default=datetime.now)  # Transaction Time
    
    def __str__(self):
        return str(self.profile) + "- bidShares: " + str(self.bidShares) + ", bidPrice: " +str(self.bidPrice)

class SellTable_""" + i.tempName + """(models.Model):
    # Table to store sell requests
    company = models.IntegerField(default=""" + str(i.pk) + """)  # Company
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)  # User
    bidPrice = models.IntegerField(default=0)  # Sell Price
    bidShares = models.IntegerField(default=0)  # Number of shares
    transactionTime = models.DateTimeField(default=datetime.now)  # Transaction Time
    
    def __str__(self):
        return str(self.profile) + "- bidShares: " + str(self.bidShares) + ", bidPrice: " +str(self.bidPrice)
    
        """)
except Exception as e:
    print(
        "Partial MakeMigrations! Please Run migrate and then makemigrations Again"
    )

bazaar/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.db import IntegrityError
from datetime import datetime
from django.http import JsonResponse
import json
import requests
import random
from .models import *
from .matchUtilities import *
from .utility import *
# Create your views here.
buyTable = None
sellTable = None


class Register(View):
    template = 'bazaar/register.html'

    def get(self, request):
        return render(request, self.template, {})

    def post(self, request):
        try:
            # add_company("")
            g = Global.objects.get(pk=1)
            print(g.registrationKey)
            if request.POST["password"] == g.registrationKey:
                user = User.objects.create_user(
                    username=request.POST["username"])
                password = User.objects.make_random_password(length=6)
                user.set_password(password)
                user.save()

                profile = Profile.objects.create(user=user)
                profile.save()
                return render(request, self.template, {"pass": password})
            return render(request, self.template,
                          {"error": "Invalid Registration"})
        except IntegrityError:
            return render(request, self.template,
                          {"error": "Invalid Registration"})


def requestUser(username, password):
    print()
    print("Requesting ", username)
    print()
    api_endpoint = "https://backend.credenz.in/eventlogin"
    data = {
        "username": username,
        "password": password,
        "adminpass": "pass",
        "event": "wallstreet"
    }
    r = requests.post(url=api_endpoint, data=data)
    userdets = r.json()
    print()
    print("Api Request, user details : ")
    print(userdets)
    print()
    return userdets


def createUser(userdets):
    print()
    print("Creating ", userdets)
    print()
    username = userdets['user']['username']
    password = userdets['user']['password']
    email = userdets['user']['email']
    name = userdets['user']['name']
    user = User.objects.create_user(username=username,
                                    password=password,
                                    email=email)
    user.first_name = name
    user.save()
    profile = Profile.objects.create(user=user)
    profile.save()
    print()
    print(username + " created and saved")
    print()


class Login(View):
    template = 'bazaar/login.html'
    template1 = 'bazaar/index.html'

    def get(self, request):
        if request.user.is_authenticated:
            return redirect('../')
        return render(request, self.template, {})

    def post(self, request):
        username = request.POST["username"]
        password = request.POST["password"]

        if username == "" or password == "":
            message = "Missing username or password"
            context = {"message": message}
            return render(request, self.template, context)

        user = authenticate(username=username, password=password)

        if user is not None:
            if user.is_active:
                print()
                print("User in DB")
                print()
                login(request, user)
                return redirect("../")
        else:
            # message = "Invalid Username or Password!"
            # context = {"message": message}
            # return render(request, self.template, context)
            print()
            print("User not in DB")
            print()
            newuser = requestUser(username, password)
            if newuser["allow"]:
                createUser(newuser)
                user = authenticate(username=username, password=password)
                login(request, user)
                return redirect("../")
            else:
                message = "Invalid Username or Password!"
                context = {"message": message}
                return render(request, self.template, context)


def Logoff(request):
    if request.user.is_authenticated:
        logout(request)
    return redirect("../login")


class postlogin(View):
    template = 'bazaar/index.html'

    def get(self, request):
        if not request.user.is_authenticated:
            return redirect('/login')
        all_companies = Company.objects.all()
        profile = Profile.objects.filter(user=User.objects.get(
            username=request.user)).first()
        shares = UserShareTable.objects.filter(profile=profile)
        sensex = Global.objects.filter(pk=1).first().sensex
        g = Global.objects.get(pk=1)
        context = {
            "companies": all_companies,
            "profile": profile,
            "userShareTable": shares,
            "sensex": sensex,
            "livetext": g.LiveText
        }
        return render(request, self.template, context)


class CompanyView(View):
    template = 'bazaar/company.html'

    def get(self, request):
        profile = Profile.objects.filter(user=User.objects.get(
            username=request.user)).first()
        sensex = Global.objects.filter(pk=1).first().sensex
        companies = Company.objects.all()
        context = {
            "profile": profile,
            "sensex": sensex,
            "companies": companies
        }
        return render(request, self.template, context)


class Buy(View):
    template = 'bazaar/buy.html'
    error = 'bazaar/marketclose.html'
    context = {}

    # ToDo: Add validations in frontend
    def get(self, request):
        startStopMarket = Global.objects.get(pk=1).startStopMarket
        if startStopMarket:
            profile = Profile.objects.filter(user=User.objects.get(
                username=request.user)).first()
            sensex = Global.objects.filter(pk=1).first().sensex
            companies = list(Company.objects.all())
            random.shuffle(companies)
            bidRange = Global.objects.filter(pk=1).first().bidRangePercent
            context = {
                'companies': companies,
                "profile": profile,
                "sensex": sensex,
                "bidRange": bidRange
            }
            return render(request, self.template, context)
        else:
            return render(request, self.error)

    def post(self, request, *args, **kwargs):
        startStopMarket = Global.objects.get(pk=1).startStopMarket

        if startStopMarket:
            companyName = request.POST["companyName"].split(' :')[0]
            company = Company.objects.get(name__contains=companyName)
            profile = Profile.objects.filter(user=User.objects.get(
                username=request.user)).first()
            sensex = Global.objects.filter(pk=1).first().sensex
            bidRange = Global.objects.filter(
                pk=1).first().bidRangePercent / 100
            bidShares = 0
            bidPrice = 0
            exec("global buyTable; buyTable = BuyTable_" + company.tempName)
            try:
                if request.POST["quantity"] and request.POST["price"]:
                    bidShares = int(request.POST["quantity"])
                    bidPrice = int(request.POST["price"])
                else:
                    companies = Company.objects.all()
                    context = {
                        'companies': companies,
                        "bidRange": bidRange,
                        "message": "Please Fill All The Fields",
                        "profile": profile,
                        "sensex": sensex
                    }
                    return render(request, self.template, context)
            except:
                companies = Company.objects.all()
                context = {
                    'companies': companies,
                    "bidRange": bidRange,
                    "message": "Invalid Bid",
                    "profile": profile,
                    "sensex": sensex
                }
                return render(request, self.template, context)

            if 0 < bidShares <= 100 and bidPrice > 0 and (
                    1 - bidRange
            ) * company.sharePrice <= bidPrice <= (
                    1 + bidRange
            ) * company.sharePrice and profile.cash > 0 and profile.cash >= bidShares * bidPrice * 1.01:
                #moneyAlter(profile, bidPrice * bidShares, False)  # Subtract money for user

                moneyAlter(profile, bidPrice * bidShares,
                           False)  # Subtract money for user
                buyTable.objects.create(
                    company=company.pk,
                    profile=profile,
                    bidShares=bidShares,
                    bidPrice=bidPrice)  # Add entry to buyTable

                match.delay(company, profile, bidPrice, bidShares, True)

                return render(request, 'bazaar/received_bid.html', {})
            else:
                companies = Company.objects.all()
                context = {
                    'companies': companies,
                    "bidRange": bidRange,
                    "message": "Invalid Bid",
                    "profile": profile,
                    "sensex": sensex
                }
                return render(request, self.template, context)
        else:
            return render(request, self.error)


class Sell(View):
    template = 'bazaar/sell.html'
    error = 'bazaar/marketclose.html'

    # ToDo: Add validations in frontend
    def get(self, request):
        startStopMarket = Global.objects.get(pk=1).startStopMarket
        if startStopMarket:
            companies = []
            user = User.objects.get(username=request.user)
            profile = Profile.objects.filter(user=User.objects.get(
                username=request.user)).first()
            sensex = Global.objects.filter(pk=1).first().sensex
            userShares = UserShareTable.objects.filter(

bazaar/templates/bazaar/buy.html
{%load static%}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Welcome to Wallstreet!</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="{% static 'bazaar/vendor/bootstrap/css/bootstrap.min.css'%}">
    <!-- Font Awesome CSS-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <!-- Google fonts - Popppins for copy-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,800">
    <!-- orion icons-->
    <link rel="stylesheet" href="{% static 'bazaar/css/orionicons.css'%}">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="{% static 'bazaar/css/style.default.css'%}" id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="{% static 'bazaar/css/custom.css'%}">
    <!-- Favicon-->
    <link rel="shortcut icon" href="{% static 'bazaar/img/favicon.png'%}">


    <style type="text/css">
        #loading {
            width: 100%;
            height: 100vh;
            background: #000;
        }
        
        .page-holder {
            background: url('{% static 'bazaar/img/1.png'%}');
            background-attachment: fixed;
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover;
        }
    </style>
</head>

<body onload="start()">
    <div id="loading"></div>
    <!-- navbar-->
    <header class="header">
        <nav class="navbar sticky-top navbar-expand-lg px-4 py-2 bg-white shadow">
        <a href="#" class="sidebar-toggler text-gray-500 mr-4 mr-lg-5 lead">
        <i class="fas fa-align-left"></i></a>
        <img src = "{% static "bazaar/img/cs.png" %}" height="20">  
        <a href="#" class="navbar-brand font-weight-bold text-uppercase text-base">Wallstreet</a>
            <ul class="ml-auto d-flex align-items-center list-unstyled mb-0">

                <li class="nav-item dropdown mr-3"><a id="notifications" href="http://example.com" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="nav-link dropdown-toggle text-gray-400 px-1"><i class="fa fa-bell"></i><span class="notification-icon"></span></a>
                    <div aria-labelledby="notifications" class="dropdown-menu">
                        <a href="{% url 'bazaar:news' %}" class="dropdown-item text-center"><small class="font-weight-bold headings-font-family text-uppercase">View News</small></a>
                    </div>
                </li>
                <li class="nav-item dropdown ml-auto">
                    <a id="userInfo" href="http://example.com" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="nav-link dropdown-toggle"><img src="{% static 'bazaar/img/navLogo.png' %}" alt="Jason Doe" style="max-width: 1.5rem;" class="img-fluid rounded-circle shadow"></a>
                    <div aria-labelledby="userInfo" class="dropdown-menu"><a href="#" class="dropdown-item"><strong class="d-block text-uppercase headings-font-family">{{ profile.user.username }}</strong><small>Cash: {{ profile.cash }}</small><br/><small>Net Worth: {{ profile.netWorth }}</small><br/><small>Rank: {{ profile.rank }}</small></a>
                        <div class="dropdown-divider"></div><a href="../#sectionMyShares" class="dropdown-item">Your Shares</a>
                        <div class="dropdown-divider"></div><a href="{% url 'bazaar:transactions' %}" class="dropdown-item">Transaction History</a>
                        <div class="dropdown-divider"></div><a href="{%url 'bazaar:logoff'%}" class="dropdown-item">Logout</a>
                    </div>
                </li>
            </ul>
        </nav>
    </header>
    <div class="d-flex align-items-stretch">
        <div id="sidebar" class="sidebar py-3">
            <div class="text-gray-400 text-uppercase px-3 px-lg-4 py-4 font-weight-bold small headings-font-family">MAIN</div>
            <ul class="sidebar-menu list-unstyled" style="margin-left:-15px;">
                <li class="sidebar-list-item"><a href="{%url 'bazaar:index' %}" class="sidebar-link text-muted"><i class="o-home-1 mr-3 text-gray"></i><span>Home</span></a></li>
                <li class="sidebar-list-item"><a href="{% static 'bazaar/Wallstreet_Portfolios.pdf' %}" class="sidebar-link text-muted"><i class="o-table-content-1 mr-3 text-gray"></i><span>Company Info</span></a></li>
                <li class="sidebar-list-item"><a href="../#sectionMyShares" class="sidebar-link text-muted"><i class="o-table-content-1 mr-3 text-gray"></i><span>Your Shares</span></a></li>
                <li class="sidebar-list-item"><a href="{%url 'bazaar:buy' %}" class="sidebar-link text-muted active"><i class="o-sales-up-1 mr-3 text-gray"></i><span>Buy</span></a></li>
                <li class="sidebar-list-item"><a href="{%url 'bazaar:sell' %}" class="sidebar-link text-muted"><i class="o-sales-up-1 mr-3 text-gray"></i><span>Sell</span></a></li>
                <li class="sidebar-list-item"><a href="{%url 'bazaar:news' %}" class="sidebar-link text-muted"><i class="o-table-content-1 mr-3 text-gray"></i><span>News</span></a></li>
                <li class="sidebar-list-item"><a href="{%url 'bazaar:transactions' %}" class="sidebar-link text-muted"><i class="o-table-content-1 mr-3 text-gray"></i><span>Transactions</span></a></li>
                <li class="sidebar-list-item"><a href="{%url 'bazaar:leaderboard' %}" class="sidebar-link text-muted"><i class="o-survey-1 mr-3 text-gray"></i><span>Leaderboard</span></a></li>

                <li class="sidebar-list-item"><a href="{%url 'bazaar:logoff'%}" class="sidebar-link text-muted"><i class="o-exit-1 mr-3 text-gray"></i><span>Logout</span></a></li>
            </ul>

        </div>
        <p style="display:none;" id="bidRange">{{ bidRange }}</p>

        <div class="page-holder w-100 d-flex flex-wrap">
            <div class="container-fluid px-xl-5">
                <section class="py-5">

                    <div class="row d-flex justify-content-center align-items-center">

                        <div class="col-lg-6 mb-5">
                            <div class="card">
                                <div class="card-header">
                                    <h3 class="h6 text-uppercase mb-0" align="text-center">Buy</h3>

                                </div>
                                <div class="card-body">
                                    <p style="color: red">* Value beside the company indicates current share price</p>
                                    {% if message %}
                                    <p style="color: red">{{message}}</p>
                                    {% endif %}
                                    <p id="validation" style="color: red;display: none">Invalid Bid</p>
                                    <p id="cashValidation" style="color: red;display: none">You do not have enough cash to buy the shares</p>
                                    <form action="/buy/" id="buyForm" method="post">
                                        {%csrf_token%}
                                        <div class="form-group">

                                            <div class="select">
                                                <label class="form-control-label text-uppercase">Company</label>
                                                <select id="company" name="companyName" class="form-control" style="width: 100%" form="buyForm">
                                {% for company in companies %}
                                <option style="color: black">{{ company.name }} :   Rs.{{ company.sharePrice }}</p></option>
                                {% endfor %}
                              </select>
                                            </div>


                                        </div>
                                        <div class="form-group">
                                            <label class="form-control-label text-uppercase">Quantity</label>
                                            <input id="quantity" type="text" placeholder="Quantity" class="form-control" name="quantity">
                                        </div>
                                        <div class="form-group">
                                            <label class="form-control-label text-uppercase">Bid Price</label>
                                            <input id="bidPrice" type="text" placeholder="Bid Price" class="form-control" name="price">
                                        </div>
                                        <div class="form-group">
                                            <button id="submitForm" type="submit" class="btn btn-primary">Submit</button>

                                        </div>
                                    </form>
                                    <p id="cash" style="display: none">{{profile.cash}}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
            <footer class="footer bg-white shadow align-self-end py-3 px-xl-5 w-100">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-6 text-center text-md-left text-primary">
                            <p class="mb-2 mb-md-0">When it is a question of money, everyone is of the same religion</p>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script>
        var preloader = document.getElementById('loading');

        function start() {
            preloader.style.display = 'none';
        }
    </script>



    <!-- JavaScript files<script src="{% static 'bazaar/js/buy_validation.js' %}"></script>-->
    <script src="{% static 'bazaar/vendor/jquery/jquery.min.js'%}"></script>
    <script src="{% static 'bazaar/vendor/popper.js/umd/popper.min.js'%}">
    </script>
    <script src="{% static 'bazaar/vendor/bootstrap/js/bootstrap.min.js'%}"></script>
    <script src="{% static 'bazaar/vendor/jquery.cookie/jquery.cookie.js'%}">
    </script>
    <script src="{% static 'bazaar/vendor/chart.js/Chart.min.js'%}"></script>
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
    <script src="{% static 'bazaar/js/charts-custom.js'%}"></script>
    <script src="{% static 'bazaar/js/front.js'%}"></script>

</body>

</html>